### PR TITLE
Update key_people page to gen. random people

### PR DESCRIPTION
**Pull request by Cruikshanks**

### CODE REVIEW

**Comment by Cruikshanks** [comment]
And the code for the `upper_tier_limited_company_registration_steps.rb` step

```ruby
people = @app.key_people_page.key_people
@app.key_people_page.add_director(person: people[0])
@app.key_people_page.add_director(person: people[1])
@app.key_people_page.submit_director(person: people[2])
```

**Comment by Cruikshanks** [comment]
https://github.com/stympy/faker

**Comment by timstone** [comment]
@Cruikshanks I'm getting `undefined method `first_name' for #<Hash:0x007fd445bb7f80> (NoMethodError)`
I've pushed up my branch with updates

**Comment by Cruikshanks** [comment]
Got it all working locally now @timstone

**Pull request merged**
